# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/vampiro/Downloads/Linux_Unreal_Engine_5.4.4
GAMEPROJECTFILE =/home/vampiro/Documents/Unreal Projects/AI4FOREST/AI4FOREST.uproject

TARGETS = \
	AI4FOREST-Linux-DebugGame  \
	AI4FOREST-Linux-Shipping  \
	AI4FOREST \
	AI4FORESTEditor-Linux-DebugGame  \
	AI4FORESTEditor-Linux-Shipping  \
	AI4FORESTEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend AI4FORESTEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug AI4FORESTEditor-Linux-Debug


AI4FOREST-Linux-DebugGame:
	 $(PROJECTBUILD) AI4FOREST Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AI4FOREST-Linux-Shipping:
	 $(PROJECTBUILD) AI4FOREST Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

AI4FOREST:
	 $(PROJECTBUILD) AI4FOREST Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

AI4FORESTEditor-Linux-DebugGame:
	 $(PROJECTBUILD) AI4FORESTEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AI4FORESTEditor-Linux-Shipping:
	 $(PROJECTBUILD) AI4FORESTEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

AI4FORESTEditor:
	 $(PROJECTBUILD) AI4FORESTEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
